### ISSUE TITLE
Fastest Way to Access Annotated Dataset? 

### ISSUE THREAD

**Issue by parkervg** [TAG-Research/TAG-Bench#3]
Hi, thanks for the very cool work!

I'm the maintainer of [BlendSQL](https://github.com/parkervg/blendsql), and am looking to do some research into evaluations on your TAG benchmark. After following the steps in your README, it seems as though [hand_written.py](https://github.com/TAG-Research/TAG-Bench/blob/main/tag/hand_written.py) is the only place containing the gold question/answer annotations (of course i could be wrong here)

Is parsing the hand_written.py file currently the recommended way to get access to the dataset?

**Comment by parkervg** [comment]
Sorry for flip-flopping on this issue - I just noticed some discrepancies between the content of `tag_queries.csv` and the `hand_written.py` file, and am curious which should be used to perform the same benchmark described in your paper.

Query id 6 in tag_queries.csv:

> Among the root posts owned by csgillespie, what is the id of the post I could reference to answer my question about ordinary least squares?

`pipeline_6()` in hand_written.py:

>     query = "Among the posts owned by csgillespie, how many of them are root posts and mention academic papers?"

**Comment by abiswal2001** [comment]
Thanks for catching the discrepancies. These should hopefully be fixed now and tag_queries.csv contains the exact queries we used in our benchmark (and in handwritten.py).
